# Generated by Django 2.1.7 on 2023-04-18 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230418_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 18, 20, 51, 22, 799141)),
        ),
    ]
